In [3]:
import tensorflow as tf 


# TensorFlow

In [4]:
zero_d = tf.constant(0)
print(zero_d)

tf.Tensor(0, shape=(), dtype=int32)


In [5]:
one_d = tf.constant([1,2,3])
one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
two_d = tf.constant([[1,2,3],[4,5,6]])
two_d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:
a=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
three_d =tf.constant(a)
three_d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [9]:
two_d.shape

TensorShape([2, 3])